version: "3.7"
services:

  torrent-client:
    image: lscr.io/linuxserver/deluge
    restart: unless-stopped
    network_mode: service:vpn-sidecar
    depends_on:
      - vpn-sidecar
    volumes:
      - deluge-data-volume:/config
      - downloads-volume:/downloads

  web-proxy:
    image: dperson/nginx
    restart: unless-stopped
    networks:
      - default
      - isolated_torrent_network
    environment:
      - PROXY=http://torrent-client:8112;/
    ports:
      - 8112:80
    links:
      - vpn-sidecar:torrent-client
    depends_on:
      - torrent-client
    read_only: true
    tmpfs:
      - /run
      - /tmp
      - /var/cache/nginx

  vpn-sidecar:
    image: dperson/openvpn-client
    restart: unless-stopped
    networks:
      - isolated_torrent_network
    cap_add:
      - NET_ADMIN
    read_only: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - openvpn-client-config-volume:/vpn
    environment:
      FIREWALL: ""
      # VPNPORT: "42069;udp"   # port forwarding for the torrent clietn
      # VPNPORT_2: "42069;tcp" # update the deluge incoming port to be the same as this
      OTHER_ARGS: "--mute-replay-warnings" # optional
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0 # for raspberry pi compatibility?

volumes:
  deluge-data-volume: # go-ipfs application files - change to a persistent location
    driver_opts:
        type: tmpfs
        device: tmpfs
  downloads-volume: # (optional) file download location - change to a persistent location
    driver_opts:
        type: tmpfs
        device: tmpfs
  openvpn-client-config-volume: # read-only location of *.ovpn
    driver: local
    driver_opts:
        o: bind
        type: none
        device: "$PWD/openvpn/"

networks:
  default:
  isolated_torrent_network:
